// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const FAX_TYPE_UNION_VALUES = ['other', 'prescription', 'test'] as const;

type FaxTypeUnion = PrettifyUnion<ZeroFieldType<'faxDocument', 'faxType'>>;

const isFaxTypeUnion = (value: unknown): value is FaxTypeUnion =>
  isString(value) && FAX_TYPE_UNION_VALUES.some((enumValue) => enumValue === value);

const isFaxTypeUnionArray = (value: unknown): value is FaxTypeUnion[] =>
  Array.isArray(value) && value.every((element) => isFaxTypeUnion(element));

export { FAX_TYPE_UNION_VALUES, isFaxTypeUnion, isFaxTypeUnionArray };

export type { FaxTypeUnion };
