// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const FILL_ORDER_SOURCE_UNION_VALUES = ['api', 'fax'] as const;

type FillOrderSourceUnion = PrettifyUnion<ZeroFieldType<'fillOrder', 'orderSource'>>;

const isFillOrderSourceUnion = (value: unknown): value is FillOrderSourceUnion =>
  isString(value) && FILL_ORDER_SOURCE_UNION_VALUES.some((enumValue) => enumValue === value);

const isFillOrderSourceUnionArray = (value: unknown): value is FillOrderSourceUnion[] =>
  Array.isArray(value) && value.every((element) => isFillOrderSourceUnion(element));

export { FILL_ORDER_SOURCE_UNION_VALUES, isFillOrderSourceUnion, isFillOrderSourceUnionArray };

export type { FillOrderSourceUnion };
