// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const INTAKE_SOURCE_TYPE_UNION_VALUES = ['fax', 'manual_upload'] as const;

type IntakeSourceTypeUnion = PrettifyUnion<ZeroFieldType<'faxDocument', 'sourceType'>>;

const isIntakeSourceTypeUnion = (value: unknown): value is IntakeSourceTypeUnion =>
  isString(value) && INTAKE_SOURCE_TYPE_UNION_VALUES.some((enumValue) => enumValue === value);

const isIntakeSourceTypeUnionArray = (value: unknown): value is IntakeSourceTypeUnion[] =>
  Array.isArray(value) && value.every((element) => isIntakeSourceTypeUnion(element));

export { INTAKE_SOURCE_TYPE_UNION_VALUES, isIntakeSourceTypeUnion, isIntakeSourceTypeUnionArray };

export type { IntakeSourceTypeUnion };
