// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const INTAKE_STATUS_UNION_VALUES = [
  'complete',
  'failed',
  'order_created',
  'processing',
  'queued',
  'rejected',
  'review_required',
] as const;

type IntakeStatusUnion = PrettifyUnion<ZeroFieldType<'faxDocument', 'status'>>;

const isIntakeStatusUnion = (value: unknown): value is IntakeStatusUnion =>
  isString(value) && INTAKE_STATUS_UNION_VALUES.some((enumValue) => enumValue === value);

const isIntakeStatusUnionArray = (value: unknown): value is IntakeStatusUnion[] =>
  Array.isArray(value) && value.every((element) => isIntakeStatusUnion(element));

export { INTAKE_STATUS_UNION_VALUES, isIntakeStatusUnion, isIntakeStatusUnionArray };

export type { IntakeStatusUnion };
