// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const ORDER_STATUS_UNION_VALUES = [
  'consultation_required',
  'hold_file',
  'in_progress',
  'labels_printed',
  'not_filled',
  'rejected',
  'shipped',
  'shipping_error',
  'shipping_pickup',
  'unverified',
  'verified',
  'waiting',
] as const;

type OrderStatusUnion = PrettifyUnion<ZeroFieldType<'fillOrder', 'orderStatus'>>;

const isOrderStatusUnion = (value: unknown): value is OrderStatusUnion =>
  isString(value) && ORDER_STATUS_UNION_VALUES.some((enumValue) => enumValue === value);

const isOrderStatusUnionArray = (value: unknown): value is OrderStatusUnion[] =>
  Array.isArray(value) && value.every((element) => isOrderStatusUnion(element));

export { isOrderStatusUnion, isOrderStatusUnionArray, ORDER_STATUS_UNION_VALUES };

export type { OrderStatusUnion };
