// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const ORDER_TYPE_UNION_VALUES = ['new_rx', 'refill'] as const;

type OrderTypeUnion = PrettifyUnion<ZeroFieldType<'fillOrder', 'orderType'>>;

const isOrderTypeUnion = (value: unknown): value is OrderTypeUnion =>
  isString(value) && ORDER_TYPE_UNION_VALUES.some((enumValue) => enumValue === value);

const isOrderTypeUnionArray = (value: unknown): value is OrderTypeUnion[] =>
  Array.isArray(value) && value.every((element) => isOrderTypeUnion(element));

export { isOrderTypeUnion, isOrderTypeUnionArray, ORDER_TYPE_UNION_VALUES };

export type { OrderTypeUnion };
