// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const POSTAL_CARRIER_UNION_VALUES = ['easypost', 'fedex', 'unknown', 'ups', 'usps'] as const;

type PostalCarrierUnion = PrettifyUnion<ZeroFieldType<'shipment', 'carrier'>>;

const isPostalCarrierUnion = (value: unknown): value is PostalCarrierUnion =>
  isString(value) && POSTAL_CARRIER_UNION_VALUES.some((enumValue) => enumValue === value);

const isPostalCarrierUnionArray = (value: unknown): value is PostalCarrierUnion[] =>
  Array.isArray(value) && value.every((element) => isPostalCarrierUnion(element));

export { isPostalCarrierUnion, isPostalCarrierUnionArray, POSTAL_CARRIER_UNION_VALUES };

export type { PostalCarrierUnion };
