// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const PRESCRIPTION_KIND_UNION_VALUES = ['formula_modification', 'initial', 'renewal', 'unknown'] as const;

type PrescriptionKindUnion = PrettifyUnion<ZeroFieldType<'faxDocument', 'prescriptionKind'>>;

const isPrescriptionKindUnion = (value: unknown): value is PrescriptionKindUnion =>
  isString(value) && PRESCRIPTION_KIND_UNION_VALUES.some((enumValue) => enumValue === value);

const isPrescriptionKindUnionArray = (value: unknown): value is PrescriptionKindUnion[] =>
  Array.isArray(value) && value.every((element) => isPrescriptionKindUnion(element));

export { isPrescriptionKindUnion, isPrescriptionKindUnionArray, PRESCRIPTION_KIND_UNION_VALUES };

export type { PrescriptionKindUnion };
