// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const PRODUCT_TYPE_UNION_VALUES = ['compound'] as const;

type ProductTypeUnion = PrettifyUnion<ZeroFieldType<'prescription', 'productType'>>;

const isProductTypeUnion = (value: unknown): value is ProductTypeUnion =>
  isString(value) && PRODUCT_TYPE_UNION_VALUES.some((enumValue) => enumValue === value);

const isProductTypeUnionArray = (value: unknown): value is ProductTypeUnion[] =>
  Array.isArray(value) && value.every((element) => isProductTypeUnion(element));

export { isProductTypeUnion, isProductTypeUnionArray, PRODUCT_TYPE_UNION_VALUES };

export type { ProductTypeUnion };
