// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: bun run generate:zero-schema

import { isString } from 'lodash-es';

import type { PrettifyUnion, ZeroFieldType } from '../types';

const USER_ROLE_UNION_VALUES = ['admin', 'partner', 'pharmacist', 'robot', 'technician'] as const;

type UserRoleUnion = PrettifyUnion<ZeroFieldType<'user', 'role'>>;

const isUserRoleUnion = (value: unknown): value is UserRoleUnion =>
  isString(value) && USER_ROLE_UNION_VALUES.some((enumValue) => enumValue === value);

const isUserRoleUnionArray = (value: unknown): value is UserRoleUnion[] =>
  Array.isArray(value) && value.every((element) => isUserRoleUnion(element));

export { isUserRoleUnion, isUserRoleUnionArray, USER_ROLE_UNION_VALUES };

export type { UserRoleUnion };
